name: Extract ZIP File

on:
  push:
    paths:
      - "*.zip"  # Runs only when a ZIP file is pushed

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract ZIP Files
        run: |
          unzip -o '*.zip' -d extracted_files
          rm *.zip  # (Optional) Remove ZIP after extraction

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add extracted_files
          git commit -m "Extracted files from ZIP"
          git push
